services:
  atom:
    container_name: atom
    image: alexandreoda/atom
    privileged: false
    environment:
      - DISPLAY
    network_mode: host
    volumes:
      - "${HOME}:/home/atom"
      - "/tmp/.X11-unix/:/tmp/.X11-unix/"
      - "/dev/bus/usb:/dev/bus/usb"