version: "3.7"

services:
  atom:
    container_name: atom
    image: alexandreoda/atom
    privileged: false
    environment:
      - DISPLAY
    volumes:
      - "${HOME}:/home/atom"
      - "/tmp/.X11-unix/:/tmp/.X11-unix/"
    network_mode: host